### PR TITLE
Added new clustering tools and reorganize existing ones

### PR DESCRIPTION
**Pull request by ltcptgeneral**
Implements #67, consider adding additional algos.

## Proposed Changes

  - create new subpackage to contain clustering tools
  - add DBSCAN clustering algorithm
  - add Spectral clustering algorithm

### CODE REVIEW

**Review by devksingh4 — APPROVED** [review]
lgtm

**Review by jlevine18 — APPROVED** [review]
Thanks for doing this. Do we want to add any other clustering methods or provide the option to fit a transformation kernel first before applying? Do we want to add an option to normalize the data before applying a clustering, either as a parameter or as a separate function?

**Comment by ltcptgeneral** [comment]
> Thanks for doing this. Do we want to add any other clustering methods or provide the option to fit a transformation kernel first before applying? Do we want to add an option to normalize the data before applying a clustering, either as a parameter or as a separate function?

Good idea, I'll look into it.

**Comment by devksingh4** [comment]
Do we even want to add normalization? It's a simple numpy call with std and mean, no? It would basically be a one-line wrapper call.

On Jul 19, 2021 6:26 PM, Arthur Lu ***@***.***> wrote:

Thanks for doing this. Do we want to add any other clustering methods or provide the option to fit a transformation kernel first before applying? Do we want to add an option to normalize the data before applying a clustering, either as a parameter or as a separate function?

Good idea, I'll look into it.

**Comment by ltcptgeneral** [comment]
> Do we even want to add normalization? It's a simple numpy call with std and mean, no? It would basically be a one-line wrapper call.

Might as well add the option

**Comment by ltcptgeneral** [comment]
Normalization preprocessing added

**Pull request merged**
